upstream univesp_sso_gateway {
	server 127.0.0.1:4000 fail_timeout=0;
}

upstream frappe_web {
	server 127.0.0.1:8000 fail_timeout=0;
}

upstream frappe_socketio {
	server 127.0.0.1:9000 fail_timeout=0;
}

map $http_upgrade $connection_upgrade {
	default upgrade;
	'' close;
}
