const routes = [
  {
    path: '/acesso-local/:profileKey?',
    name: 'local-access',
    component: () => import('@/pages/LocalAccessPage.vue'),
    meta: {
      title: 'Acesso local por perfil',
      layout: 'auth',
    },
  },
  {
    path: '/login',
    name: 'login',
    component: () => import('@/pages/LoginPage.vue'),
    meta: {
      title: 'Login UNIVESP',
      layout: 'auth',
      publicOnly: true,
    },
  },
  {
    path: '/wireframes/aluno/:screenId?',
    name: 'student-wireframe',
    component: () => import('@/pages/wireframes/StudentWireframePage.vue'),
    meta: {
      title: 'Wireframe navegavel do aluno',
      layout: 'wireframe',
    },
  },
  {
    path: '/',
    name: 'overview',
    component: () => import('@/pages/OverviewPage.vue'),
    meta: {
      title: 'Visao institucional',
      stage: 'overview',
      requiresAuth: true,
      shellKey: 'governance',
      allowedProfiles: ['admin_central'],
    },
  },
  {
    path: '/triagem',
    name: 'triage',
    component: () => import('@/pages/TriagePage.vue'),
    meta: {
      title: 'Entrada e triagem',
      stage: 'triage',
      requiresAuth: true,
      shellKey: 'governance',
      allowedProfiles: ['admin_central'],
    },
  },
  {
    path: '/ticket',
    name: 'ticket',
    component: () => import('@/pages/TicketPage.vue'),
    meta: {
      title: 'Registro do protocolo',
      stage: 'ticket',
      requiresAuth: true,
      shellKey: 'governance',
      allowedProfiles: ['admin_central'],
    },
  },
  {
    path: '/handoff',
    name: 'handoff',
    component: () => import('@/pages/HandoffPage.vue'),
    meta: {
      title: 'Escalacao humana',
      stage: 'handoff',
      requiresAuth: true,
      shellKey: 'governance',
      allowedProfiles: ['admin_central'],
    },
  },
  {
    path: '/integracoes',
    name: 'integrations',
    component: () => import('@/pages/IntegrationsPage.vue'),
    meta: {
      title: 'Integracoes e governanca',
      stage: 'integrations',
      requiresAuth: true,
      shellKey: 'governance',
      allowedProfiles: ['admin_central'],
    },
  },
  {
    path: '/aluno',
    name: 'student-home',
    component: () => import('@/pages/student/StudentHomePage.vue'),
    meta: {
      title: 'Como podemos ajudar?',
      stage: 'student-home',
      requiresAuth: true,
      shellKey: 'student',
      allowedProfiles: ['aluno'],
    },
  },
  {
    path: '/aluno/duvida',
    name: 'student-journey',
    component: () => import('@/pages/student/StudentJourneyPage.vue'),
    meta: {
      title: 'Tenho uma duvida',
      stage: 'student-journey',
      requiresAuth: true,
      shellKey: 'student',
      allowedProfiles: ['aluno'],
    },
  },
  {
    path: '/aluno/solicitacoes',
    name: 'student-requests',
    component: () => import('@/pages/student/StudentRequestsPage.vue'),
    meta: {
      title: 'Minhas solicitacoes',
      stage: 'student-requests',
      requiresAuth: true,
      shellKey: 'student',
      allowedProfiles: ['aluno'],
    },
  },
  {
    path: '/aluno/protocolo',
    name: 'student-protocol',
    component: () => import('@/pages/student/StudentProtocolPage.vue'),
    meta: {
      title: 'Continuar com a solicitacao',
      stage: 'student-protocol',
      requiresAuth: true,
      shellKey: 'student',
      allowedProfiles: ['aluno'],
    },
  },
  {
    path: '/aluno/confirmacao/:protocolId',
    name: 'student-confirmation',
    component: () => import('@/pages/student/StudentConfirmationPage.vue'),
    meta: {
      title: 'Confirmacao',
      stage: 'student-confirmation',
      requiresAuth: true,
      shellKey: 'student',
      allowedProfiles: ['aluno'],
    },
  },
  {
    path: '/aluno/solicitacoes/:protocolId',
    name: 'student-request-detail',
    component: () => import('@/pages/student/StudentRequestDetailPage.vue'),
    meta: {
      title: 'Detalhe da solicitacao',
      stage: 'student-request-detail',
      requiresAuth: true,
      shellKey: 'student',
      allowedProfiles: ['aluno'],
    },
  },
  {
    path: '/op/fila',
    name: 'operator-queue',
    component: () => import('@/pages/operator/OperatorQueuePage.vue'),
    meta: {
      title: 'Atendimentos',
      stage: 'operator-queue',
      requiresAuth: true,
      shellKey: 'operational',
      allowedProfiles: ['op', 'gestor_polos'],
      requiredActions: ['view_case'],
    },
  },
  {
    path: '/op/fila/:caseId',
    name: 'operator-case-detail',
    component: () => import('@/pages/operator/OperatorCaseDetailPage.vue'),
    meta: {
      title: 'Analise do caso',
      stage: 'operator-case-detail',
      requiresAuth: true,
      shellKey: 'operational',
      allowedProfiles: ['op', 'gestor_polos'],
      requiredActions: ['view_case'],
    },
  },
  {
    path: '/op/playbook',
    name: 'operator-playbook',
    component: () => import('@/pages/operator/OperatorGuidancePage.vue'),
    meta: {
      title: 'Consultar orientacao',
      stage: 'operator-playbook',
      requiresAuth: true,
      shellKey: 'operational',
      allowedProfiles: ['op', 'gestor_polos'],
      requiredActions: ['view_case'],
    },
  },
  {
    path: '/op/novo-atendimento',
    name: 'operator-assisted-intake',
    component: () => import('@/pages/operator/OperatorPlaybookPage.vue'),
    meta: {
      title: 'Abrir atendimento em nome do aluno',
      stage: 'operator-assisted-intake',
      requiresAuth: true,
      shellKey: 'operational',
      allowedProfiles: ['op', 'gestor_polos'],
      requiredActions: ['view_case'],
    },
  },
  {
    path: '/area/operacao',
    name: 'area-manager-home',
    component: () => import('@/pages/area/AreaManagerHomePage.vue'),
    meta: {
      title: 'Operacao da area',
      stage: 'area-manager-home',
      requiresAuth: true,
      shellKey: 'operational',
      allowedProfiles: ['gestor_area'],
      requiredActions: ['view_case'],
    },
  },
  {
    path: '/area/fila',
    name: 'area-queue',
    component: () => import('@/pages/area/AreaQueuePage.vue'),
    meta: {
      title: 'Fila da area',
      stage: 'area-queue',
      requiresAuth: true,
      shellKey: 'operational',
      allowedProfiles: ['analista_area', 'gestor_area'],
      requiredActions: ['view_case'],
    },
  },
  {
    path: '/area/fila/:caseId',
    name: 'area-case-detail',
    component: () => import('@/pages/area/AreaCaseDetailPage.vue'),
    meta: {
      title: 'Analise da area',
      stage: 'area-case-detail',
      requiresAuth: true,
      shellKey: 'operational',
      allowedProfiles: ['analista_area', 'gestor_area'],
      requiredActions: ['view_case'],
    },
  },
  {
    path: '/area/orientacao',
    name: 'area-guidance',
    component: () => import('@/pages/area/AreaGuidancePage.vue'),
    meta: {
      title: 'Conteudo vigente da area',
      stage: 'area-guidance',
      requiresAuth: true,
      shellKey: 'operational',
      allowedProfiles: ['analista_area', 'gestor_area'],
      requiredActions: ['view_area_guidance'],
    },
  },
  {
    path: '/area/mudancas',
    name: 'area-knowledge-review',
    component: () => import('@/pages/area/AreaKnowledgeReviewPage.vue'),
    meta: {
      title: 'Mudancas pendentes',
      stage: 'area-knowledge-review',
      requiresAuth: true,
      shellKey: 'operational',
      allowedProfiles: ['gestor_area'],
      requiredActions: ['approve_knowledge'],
    },
  },
  {
    path: '/area/governanca',
    name: 'area-governance',
    component: () => import('@/pages/area/AreaGovernancePage.vue'),
    meta: {
      title: 'Regras operacionais da area',
      stage: 'area-governance',
      requiresAuth: true,
      shellKey: 'operational',
      allowedProfiles: ['gestor_area'],
      requiredActions: ['manage_area_scope'],
    },
  },
  {
    path: '/admin/dashboard',
    name: 'admin-dashboard',
    component: () => import('@/pages/admin/AdminDashboardPage.vue'),
    meta: {
      title: 'Dashboard geral',
      stage: 'admin-dashboard',
      requiresAuth: true,
      shellKey: 'governance',
      allowedProfiles: ['admin_central'],
      requiredActions: ['view_case'],
    },
  },
  {
    path: '/admin/faq',
    name: 'admin-faq',
    component: () => import('@/pages/admin/AdminFaqLibraryPage.vue'),
    meta: {
      title: 'Biblioteca de fluxos FAQ',
      stage: 'admin-faq',
      requiresAuth: true,
      shellKey: 'governance',
      allowedProfiles: ['admin_central'],
      requiredActions: ['edit_faq'],
    },
  },
  {
    path: '/admin/faq/:bundleId',
    name: 'admin-faq-flow',
    component: () => import('@/pages/admin/AdminFaqPage.vue'),
    meta: {
      title: 'Visao do fluxo FAQ',
      stage: 'admin-faq',
      requiresAuth: true,
      shellKey: 'governance',
      allowedProfiles: ['admin_central'],
      requiredActions: ['edit_faq'],
    },
  },
  {
    path: '/admin/faq/:bundleId/editor',
    name: 'admin-faq-builder',
    component: () => import('@/pages/admin/AdminFaqEditorPage.vue'),
    meta: {
      title: 'Builder de fluxo FAQ',
      stage: 'admin-faq',
      layout: 'auth',
      requiresAuth: true,
      shellKey: 'governance',
      allowedProfiles: ['admin_central'],
      requiredActions: ['edit_faq'],
    },
  },
  {
    path: '/admin/parametros',
    name: 'admin-parameters',
    component: () => import('@/pages/admin/AdminParametersPage.vue'),
    meta: {
      title: 'Parametros de SLA e criticidade',
      stage: 'admin-parameters',
      requiresAuth: true,
      shellKey: 'governance',
      allowedProfiles: ['admin_central'],
      requiredActions: ['edit_parameters'],
    },
  },
  {
    path: '/admin/permissoes',
    name: 'admin-permissions',
    component: () => import('@/pages/admin/AdminPermissionsPage.vue'),
    meta: {
      title: 'Permissoes e visibilidade',
      stage: 'admin-permissions',
      requiresAuth: true,
      shellKey: 'governance',
      allowedProfiles: ['admin_central'],
      requiredActions: ['view_audit'],
    },
  },
  {
    path: '/admin/publicacao',
    name: 'admin-versioning',
    component: () => import('@/pages/admin/AdminVersioningPage.vue'),
    meta: {
      title: 'Publicacao e historico de versoes',
      stage: 'admin-versioning',
      requiresAuth: true,
      shellKey: 'governance',
      allowedProfiles: ['admin_central'],
      requiredActions: ['publish_version'],
    },
  },
]

export default routes
